function [data] = grid_ctds(cruise,gridcoord,bins)

for istation = 1:length(cruise)
    data.lon(1,istation) = cruise(istation).lon;
    data.lat(1,istation) = cruise(istation).lat;
    data.botdepth(1,istation) = cruise(istation).botdepth;
    eval(['z0 = cruise(istation).',gridcoord,';']);
    [gamma,e1,e2] = eos80_legacy_gamma_n(cruise(istation).salin,...
        cruise(istation).temp,...
        cruise(istation).press,...
        cruise(istation).lon,...
        cruise(istation).lat);
    e1(isnan(e1)) = 0;
    e2(isnan(e2)) = 0;
    gamma_e1 = gamma-e1;
    gamma_e2 = gamma+e2;
    
    gamma_t1 = eos80_legacy_gamma_n(cruise(istation).salin,...
        cruise(istation).temp-0.001,...
        cruise(istation).press,...
        cruise(istation).lon,...
        cruise(istation).lat);
    gamma_s1 = eos80_legacy_gamma_n(cruise(istation).salin-0.002,...
        cruise(istation).temp,...
        cruise(istation).press,...
        cruise(istation).lon,...
        cruise(istation).lat);
    gamma_t2 = eos80_legacy_gamma_n(cruise(istation).salin,...
        cruise(istation).temp+0.001,...
        cruise(istation).press,...
        cruise(istation).lon,...
        cruise(istation).lat);
    gamma_s2 = eos80_legacy_gamma_n(cruise(istation).salin+0.002,...
        cruise(istation).temp,...
        cruise(istation).press,...
        cruise(istation).lon,...
        cruise(istation).lat);

    [~,id] = unique(z0);
    inan = find(~isnan(cruise(istation).temp));
    id = intersect(inan,id);
    data.bin_temp(:,istation) = interp1(z0(id),cruise(istation).temp(id),bins);
    data.bin_salin(:,istation) = interp1(z0(id),cruise(istation).salin(id),bins);
%     t = data.bin_temp(:,istation);
%     s = data.bin_salin(:,istation);
%     gridgamma = nan(size(data.bin_temp(:,istation)));
%     gridgamma1 = nan(size(data.bin_temp(:,istation)));
%     gridgamma2 = nan(size(data.bin_temp(:,istation)));
%     [m0,m1,m2] = eos80_legacy_gamma_n...
%         (s(~isnan(t)&~isnan(s)),...
%         t(~isnan(t)&~isnan(s)),...
%         bins(~isnan(t)&~isnan(s))',...
%         data.lon(istation),...
%         data.lat(istation));
%     gridgamma(~isnan(t)&~isnan(s)) = m0;
%     gridgamma1(~isnan(t)&~isnan(s)) = m1;
%     gridgamma2(~isnan(t)&~isnan(s)) = m2;
%     clear m0 m1 m2;
%     data.bin_gamma_grid(:,istation) = gridgamma;
%     data.bin_gamma_grid_e1(:,istation) = gridgamma1;
%     data.bin_gamma_grid_e2(:,istation) = gridgamma2;
%     clear gridgamma gridgamma1 gridgamma2;
    data.bin_gamma(:,istation) = interp1(z0(id),gamma(id),bins);
    data.bin_gamma_e1(:,istation) = interp1(z0(id),gamma_e1(id),bins);
    data.bin_gamma_e2(:,istation) = interp1(z0(id),gamma_e2(id),bins);
    data.bin_gamma_t1(:,istation) = interp1(z0(id),gamma_t1(id),bins);
    data.bin_gamma_t2(:,istation) = interp1(z0(id),gamma_t2(id),bins);
    data.bin_gamma_s1(:,istation) = interp1(z0(id),gamma_s1(id),bins);
    data.bin_gamma_s2(:,istation) = interp1(z0(id),gamma_s2(id),bins);
    
end
[~,data.bin_press] = meshgrid(data.lon,bins);

